version: "3.9"

services:
  db:
    image: postgres:16
    container_name: zorvyn-db
    environment:
      POSTGRES_DB: assignment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - zorvyn_pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: zorvyn-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/assignment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  zorvyn_pgdata:
